
const USER_ROLES = {
    ADMIN: 'ADMIN',
    DOCTOR: 'DOCTOR',
    PATIENT: 'PATIENT'
};

const DOCTOR_TYPES = {
    MEDICAL_DOCTOR: 'MEDICAL_DOCTOR',
    LAB_TECHNICIAN: 'LAB_TECHNICIAN'
};

const DIAGNOSIS_STATUS = {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED'
};

const USER_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
};

const APPOINTMENT_STATUS = {
    SCHEDULED: 'SCHEDULED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    RESCHEDULED: 'RESCHEDULED',
    OVERDUE: 'OVERDUE'
};

module.exports = {
    USER_ROLES,
    DOCTOR_TYPES,
    DIAGNOSIS_STATUS,
    USER_STATUS,
    APPOINTMENT_STATUS
};
